global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'localhost:9093' ]

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090', 'localhost:9090']
    metrics_path: /metrics

  - job_name: "DemoSite"
    tls_config:
      insecure_skip_verify: true
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['10.202.8.139:8080']
